title = "Analogy Example"


[[entities]]
name = "h"
properties = [ "position", "orientation", "holding" ]
commands = [ "move", "rotate", "grab_type1", "grab_type2", "release" ]

[[entities]]
name = "cube_1"
properties = [ "position" , "orientation"]

[[entities]]
name = "cube_2"
properties = [ "position" , "orientation"]

[[entities]]
name = "sphere_1"
properties = [ "position" , "orientation"]

[[entities]]
name = "sphere_2"
properties = [ "position" , "orientation"]

[[entities]]
name = "cyl_1"
properties = [ "position" , "orientation"]




[[properties]]
name = "position"
type = "double"
dimensionality = [3]
opcode_handle = "vec3"

[[properties]]
name = "holding"
type = "communication_id"
dimensionality = [1]
opcode_handle = "set"

[[properties]]
name = "orientation"
type = "double"
dimensionality = [4]
opcode_handle = "quat"




[[commands]]
name = "move"
type = "double"
dimensionality = [3]
opcode_handle = "vec3"

[[commands]]
name = "grab_type1"
type = "communication_id"
dimensionality = [0]

[[commands]]
name = "grab_type2"
type = "communication_id"
dimensionality = [0]

[[commands]]
name = "release"
type = "communication_id"
dimensionality = [0]

[[commands]]
name = "rotate"
type = "double"
dimensionality = [4]
opcode_handle = "quat"
