title = "Analogy Example 2"


[[entities]]
name = "h"
properties = [ "position", "rotation", "orientation", "holding" ]
commands = [ "move", "rotate", "rotate_y", "grab_type1", "grab_type2", "release" ]

[[entities]]
name = "cube_1"
properties = [ "position" , "rotation", "orientation"]


[[entities]]
name = "sphere_1"
properties = [ "position" , "rotation", "orientation"]

[[entities]]
name = "cube_2"
properties = [ "position" , "rotation", "orientation"]

[[entities]]
name = "cyl_1"
properties = [ "position" , "rotation", "orientation"]

[[entities]]
name = "cube_3"
properties = [ "position" , "rotation", "orientation"]


[[properties]]
name = "position"
type = "double"
dimensionality = [3]
opcode_handle = "vec3"

[[properties]]
name = "holding"
type = "communication_id"
dimensionality = [1]
opcode_handle = "set"

[[properties]]
name = "rotation"
type = "double"
dimensionality = [4]
opcode_handle = "quat"

[[properties]]
name = "orientation"
type = "double"
dimensionality = [1]
opcode_handle = ""




[[commands]]
name = "move"
type = "double"
dimensionality = [3]
opcode_handle = "vec3"

[[commands]]
name = "grab_type1"
type = "communication_id"
dimensionality = [0]

[[commands]]
name = "grab_type2"
type = "communication_id"
dimensionality = [0]

[[commands]]
name = "release"
type = "communication_id"
dimensionality = [0]

[[commands]]
name = "rotate"
type = "double"
dimensionality = [4]
opcode_handle = "quat"

[[commands]]
name = "rotate_y"
type = "double"
dimensionality = [1]
opcode_handle = ""
